# Artificial Neural Network

### Importing the libraries

In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [8]:
tf.__version__

'2.15.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [4]:
dataset=pd.read_excel('Folds5x2_pp.xlsx')
X=dataset.iloc[:,:-1].values
y=dataset.iloc[:,-1].values

In [9]:
print(X)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]


In [10]:
print(y)

[463.26 444.37 488.56 ... 429.57 435.74 453.28]


### Splitting the dataset into the Training set and Test set

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2, random_state=0)

## Part 2 - Building the ANN

### Initializing the ANN

In [12]:
ann = tf.keras.models.Sequential() #intializing ANN as a Sequence of layers

### Adding the input layer and the first hidden layer

In [13]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the second hidden layer

In [14]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the output layer

In [15]:
ann.add(tf.keras.layers.Dense(units=1))
#if you are doing classification with more than 2 categories you need to use softmax activation function.
#if you are doing regression, you don't need to use any activation function.

## Part 3 - Training the ANN

### Compiling the ANN

In [16]:
ann.compile(optimizer='adam', loss='mean_squared_error') #loss function for regression should be mean sqaured error

### Training the ANN model on the Training set

In [17]:
ann.fit(X_train, y_train, batch_size=32, epochs=100)

Epoch 1/100
240/240 [==============================] - 1s 2ms/step - loss: 29586.8496
Epoch 2/100
240/240 [==============================] - 0s 2ms/step - loss: 304.4179
Epoch 3/100
240/240 [==============================] - 0s 2ms/step - loss: 289.8297
Epoch 4/100
240/240 [==============================] - 0s 2ms/step - loss: 274.4758
Epoch 5/100
240/240 [==============================] - 0s 2ms/step - loss: 256.2259
Epoch 6/100
240/240 [==============================] - 0s 2ms/step - loss: 236.8222
Epoch 7/100
240/240 [==============================] - 0s 2ms/step - loss: 215.4081
Epoch 8/100
240/240 [==============================] - 0s 2ms/step - loss: 193.6611
Epoch 9/100
240/240 [==============================] - 0s 2ms/step - loss: 172.0156
Epoch 10/100
240/240 [==============================] - 0s 2ms/step - loss: 150.7128
Epoch 11/100
240/240 [==============================] - 0s 2ms/step - loss: 130.4786
Epoch 12/100
240/240 [==============================] - 0s 2ms/step - lo

### Predicting the results of the Test set

In [18]:
y_pred = ann.predict(X_test)
np.set_printoptions(precision=2)
# reshaping both in the same fashion to compare
np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1) # 1 for vertical concatenation and 0 for horizontal concatenation

60/60 [==============================] - 0s 1ms/step


array([[433.31, 431.23],
       [464.3 , 460.01],
       [467.78, 461.14],
       ...,
       [475.04, 473.26],
       [441.77, 438.  ],
       [460.98, 463.28]])